# -*- coding: utf-8 -*-
"""OpenIM channel package（出站 WebSocket）。"""
from .channel import (
    OpenIMChannel,
    build_inbound_parts,
    detect_bot_mentioned,
    parse_file_meta,
    parse_picture_meta,
    parse_sound_meta,
    parse_text_content,
    parse_video_meta,
    should_handle_inbound,
)
from .client import derive_ws_url, ws_gateway_addr
from .credentials import (
    credentials_format_report,
    decode_app_id,
    encode_app_id,
    generate_app_id,
    generate_app_secret,
    generate_credentials,
    is_app_id,
    is_app_secret,
    is_openim_user_id,
    normalize_app_id,
    open_app_secret,
    resolve_app_secret,
    resolve_identity,
    seal_app_secret,
    seal_openim_credentials,
    verify_app_secret,
)
from .ws_client import openim_sdk_available

__all__ = [
    "OpenIMChannel",
    "build_inbound_parts",
    "credentials_format_report",
    "decode_app_id",
    "detect_bot_mentioned",
    "encode_app_id",
    "generate_app_id",
    "generate_app_secret",
    "generate_credentials",
    "is_app_id",
    "is_app_secret",
    "is_openim_user_id",
    "normalize_app_id",
    "open_app_secret",
    "openim_sdk_available",
    "parse_file_meta",
    "parse_picture_meta",
    "parse_sound_meta",
    "parse_text_content",
    "parse_video_meta",
    "resolve_app_secret",
    "resolve_identity",
    "seal_app_secret",
    "seal_openim_credentials",
    "should_handle_inbound",
    "verify_app_secret",
    "derive_ws_url",
    "ws_gateway_addr",
]
